### ISSUE TITLE
Using this with a remote system

### ISSUE THREAD

**Issue by tabedzki** [dmrauch/vscode-cpp-remote-debug#1]
Hi, I'm not sure how to actually send a message so I am posting an issue.

I am trying to modify the .json file for use with my local ubuntu system and remote red-hat server.

How would you modify it for a remote server where you have a local directory (and no root access) so that our file that we want to compile is located at `/home/tabedzki/test/test1.cpp` and the compiled file is `a.out` in the same directory?

Please let me know if you need more information.

**Comment by dmrauch** [comment]
Hi @tabedzki,
thanks for your message. I have extended the step-by-step guide and hope its clearer now.
But here are some hints / comments:
- You don't need root privileges on the remote system, just `gdbserver`.
- You need to mount the remote file system locally so that you can open it in VS Code. This can be done quite comfortably in Linux Mint's Nemo. I don't have too much experience with Ubuntu's file browser but this can surely be done there as well. Alternatively, I guess you can also use `sshfs`.
- You don't need the `/home/tabedzki/test/test1.cpp` in your `launch.json` - the `"cwd": "${workspaceRoot}",` setting will handle this part correctly if you have opened the project folder in VS Code.
- You'll need to adapt the `sourceFileMap`. Just have a look at the one that I provide with the project to have a rough idea how this may look like. I hope by hovering the mouse over the `file1.cxx` tab opened in VS Code you should be able to figure out the correct setting for your case.

**Comment by tabedzki** [comment]
Ok. I think this has cleared things up a little bit; however, I have a few remaining questions (I am going to refer to the file structure provided in this repo, which I have on the remote cluster and mounted via `sshfs`):

So I think I understand what the second argument for `sourceFileMap` should be by hovering over (I get it to be `~/cluster/vscode-cpp-remote-debug/source/folder1/file1.cxx`). This is the mounted location of the remote system. 
On the remote system, it is located in `/home/tabedzki/vscode-cpp-remote-debug/source/folder1`.  Does that mean the sourceFileMap should look like
```
"sourceFileMap": {
        "/home/tabedzki/vscode-cpp-remote-debug/source/folder1/file1.cxx": "~/cluster/vscode-cpp-remote-debug/source/folder1/file1.cxx"
      },
```
or more like
```
"sourceFileMap": {
        "/": "~/cluster/vscode-cpp-remote-debug/source/folder1/file1.cxx"
      },
```
Thank you in advance.

**Comment by dmrauch** [comment]
Ok, my guess would be something like
```
"sourceFileMap": {
  "/home/tabedzki/": "~/cluster/"
},
```
I think the idea is that you don't write down individual files but rather the upmost folder level so that the debugger can jump between different source code files if needed.

**Comment by tabedzki** [comment]
That worked! I was able to get the debugger working that way. Do you know how to start the `gdbserver` every time I click debug or is that something that must be done manually every time?

**Comment by dmrauch** [comment]
> That worked! I was able to get the debugger working that way.

Great!

> Do you know how to start the `gdbserver` every time I click debug or is that something that must be done manually every time?

So far I don't know of any way of doing that automatically - if you find one, please let me know!

**Comment by tabedzki** [comment]
Alright will do. Thanks for your help!

**Comment by dmrauch** [comment]
Perhaps this might be of interest to you: https://github.com/WebFreak001/code-debug
If you can use SSH keys to connect to the remote server, perhaps this could do the trick.

**Comment by tabedzki** [comment]
Hey @dmrauch, I was able to get the other extension to work. After you install it, you need to choose "gdb over ssh" or something to that effect. Here is what my configuration.json looked like after setting it up:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "gdb",
            "request": "launch",
            "name": "Launch Program (SSH)",
            "target": "./build/debug/file1",
            "cwd": "${workspaceFolder}/",
            "ssh": {
                "host": "seas.upenn.edu",
                "cwd": "/mnt/rrio1/home/tabedzki/vscode-cpp-remote-debug",
                "keyfile": "C:/Users/tabedzki/.ssh/id_rsa",
                "user": "tabedzki"
            }
        }
    ]
}
```
